HelloWorld:
	gcc $@.c -o $@.exe -lWS2_32
	./$@.exe

MultiplePages:
	gcc $@.c -o $@.exe -lWS2_32
	./$@.exe

MoreMIMETypes:
	gcc $@.c -o $@.exe -lWS2_32
	./$@.exe

Parameters:
	gcc $@.c -o $@.exe -lWS2_32
	./$@.exe

Messenger:
	gcc $@.c -o $@.exe -lWS2_32
	./$@.exe

GenerateKeys.c:
	gcc $@.c -o $@.exe -lWS2_32
	./$@.exe

clean:
	rm *.exe